
// This file has been generated by the GUI designer. Do not modify.
namespace TestCombo
{
	public partial class QWidget
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget TestCombo.QWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "TestCombo.QWidget";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
