
// This file has been generated by the GUI designer. Do not modify.
namespace MequantaStudio.SmartQuant
{
	public partial class ImportHistoricalDataWidget
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MequantaStudio.SmartQuant.ImportHistoricalDataWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MequantaStudio.SmartQuant.ImportHistoricalDataWidget";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
		}
	}
}
