
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action startAction;
	
	private global::Gtk.Action pauseAction;
	
	private global::Gtk.Action stopAction;
	
	private global::Gtk.Action stepAction;
	
	private global::Gtk.Action startAction1;
	
	private global::Gtk.Action pauseAction1;
	
	private global::Gtk.Action stopAction1;
	
	private global::Gtk.Action stepAction1;
	
	private global::Gtk.Action resumeAction;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Button btnStart;
	
	private global::Gtk.Button btnPause;
	
	private global::Gtk.Button btnStop;
	
	private global::Gtk.Button btnStep;
	
	private global::Gtk.ComboBox cbxMode;
	
	private global::Gtk.ComboBox cbxEvent;
	
	private global::Gtk.Entry dtpPause;
	
	private global::Gtk.Button btnStatus;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.Label label9;
	
	private global::Gtk.Label lblRunnerState;
	
	private global::Gtk.Label label10;
	
	private global::Gtk.Label lblEmStatus;
	
	private global::Gtk.Toolbar toolbar4;
	
	private global::Gtk.Entry entry1;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView textview1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.startAction = new global::Gtk.Action ("startAction", null, null, "gtk-media-play");
		w1.Add (this.startAction, null);
		this.pauseAction = new global::Gtk.Action ("pauseAction", null, null, "gtk-media-pause");
		w1.Add (this.pauseAction, null);
		this.stopAction = new global::Gtk.Action ("stopAction", null, null, "gtk-media-stop");
		w1.Add (this.stopAction, null);
		this.stepAction = new global::Gtk.Action ("stepAction", null, null, "gtk-media-next");
		w1.Add (this.stepAction, null);
		this.startAction1 = new global::Gtk.Action ("startAction1", null, null, "gtk-media-play");
		w1.Add (this.startAction1, null);
		this.pauseAction1 = new global::Gtk.Action ("pauseAction1", null, null, "gtk-media-pause");
		w1.Add (this.pauseAction1, null);
		this.stopAction1 = new global::Gtk.Action ("stopAction1", null, null, "gtk-media-stop");
		w1.Add (this.stopAction1, null);
		this.stepAction1 = new global::Gtk.Action ("stepAction1", null, null, "gtk-media-next");
		w1.Add (this.stepAction1, null);
		this.resumeAction = new global::Gtk.Action ("resumeAction", null, null, "gtk-media-forward");
		w1.Add (this.resumeAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnStart = new global::Gtk.Button ();
		this.btnStart.CanFocus = true;
		this.btnStart.Name = "btnStart";
		this.btnStart.UseUnderline = true;
		this.btnStart.Label = global::Mono.Unix.Catalog.GetString ("start");
		this.hbox1.Add (this.btnStart);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnStart]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnPause = new global::Gtk.Button ();
		this.btnPause.CanFocus = true;
		this.btnPause.Name = "btnPause";
		this.btnPause.UseUnderline = true;
		this.btnPause.Label = global::Mono.Unix.Catalog.GetString ("pause");
		this.hbox1.Add (this.btnPause);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnPause]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnStop = new global::Gtk.Button ();
		this.btnStop.CanFocus = true;
		this.btnStop.Name = "btnStop";
		this.btnStop.UseUnderline = true;
		this.btnStop.Label = global::Mono.Unix.Catalog.GetString ("stop");
		this.hbox1.Add (this.btnStop);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnStop]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnStep = new global::Gtk.Button ();
		this.btnStep.CanFocus = true;
		this.btnStep.Name = "btnStep";
		this.btnStep.UseUnderline = true;
		this.btnStep.Label = global::Mono.Unix.Catalog.GetString ("step");
		this.hbox1.Add (this.btnStep);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnStep]));
		w5.Position = 3;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.cbxMode = global::Gtk.ComboBox.NewText ();
		this.cbxMode.Name = "cbxMode";
		this.hbox1.Add (this.cbxMode);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.cbxMode]));
		w6.Position = 4;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.cbxEvent = global::Gtk.ComboBox.NewText ();
		this.cbxEvent.Name = "cbxEvent";
		this.hbox1.Add (this.cbxEvent);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.cbxEvent]));
		w7.Position = 5;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.dtpPause = new global::Gtk.Entry ();
		this.dtpPause.CanFocus = true;
		this.dtpPause.Name = "dtpPause";
		this.dtpPause.Text = global::Mono.Unix.Catalog.GetString ("2014/11/11 11:11:11");
		this.dtpPause.IsEditable = true;
		this.dtpPause.InvisibleChar = '●';
		this.hbox1.Add (this.dtpPause);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.dtpPause]));
		w8.Position = 6;
		w8.Expand = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnStatus = new global::Gtk.Button ();
		this.btnStatus.CanFocus = true;
		this.btnStatus.Name = "btnStatus";
		this.btnStatus.UseUnderline = true;
		this.btnStatus.Label = global::Mono.Unix.Catalog.GetString ("status");
		this.hbox1.Add (this.btnStatus);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnStatus]));
		w9.PackType = ((global::Gtk.PackType)(1));
		w9.Position = 7;
		w9.Expand = false;
		w9.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Runner State:");
		this.hbox3.Add (this.label9);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label9]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.lblRunnerState = new global::Gtk.Label ();
		this.lblRunnerState.Name = "lblRunnerState";
		this.lblRunnerState.LabelProp = global::Mono.Unix.Catalog.GetString ("-");
		this.hbox3.Add (this.lblRunnerState);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.lblRunnerState]));
		w12.Position = 1;
		// Container child hbox3.Gtk.Box+BoxChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("EventManager Status:");
		this.hbox3.Add (this.label10);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label10]));
		w13.Position = 2;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.lblEmStatus = new global::Gtk.Label ();
		this.lblEmStatus.Name = "lblEmStatus";
		this.lblEmStatus.LabelProp = global::Mono.Unix.Catalog.GetString ("-");
		this.hbox3.Add (this.lblEmStatus);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.lblEmStatus]));
		w14.Position = 3;
		this.vbox1.Add (this.hbox3);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
		w15.Position = 1;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString (@"<ui><toolbar name='toolbar4'><toolitem name='startAction1' action='startAction1'/><toolitem name='pauseAction1' action='pauseAction1'/><toolitem name='stopAction1' action='stopAction1'/><toolitem name='stepAction1' action='stepAction1'/><toolitem name='resumeAction' action='resumeAction'/></toolbar></ui>");
		this.toolbar4 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar4")));
		this.toolbar4.Name = "toolbar4";
		this.toolbar4.ShowArrow = false;
		this.vbox1.Add (this.toolbar4);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.toolbar4]));
		w16.Position = 2;
		w16.Expand = false;
		w16.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.entry1 = new global::Gtk.Entry ();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '●';
		this.vbox1.Add (this.entry1);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.entry1]));
		w17.Position = 3;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textview1 = new global::Gtk.TextView ();
		this.textview1.CanFocus = true;
		this.textview1.Name = "textview1";
		this.GtkScrolledWindow.Add (this.textview1);
		this.vbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
		w19.Position = 4;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 612;
		this.DefaultHeight = 335;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.startAction1.Activated += new global::System.EventHandler (this.OnToolbarStart);
		this.pauseAction1.Activated += new global::System.EventHandler (this.OnToolbarPause);
		this.stopAction1.Activated += new global::System.EventHandler (this.OnToolbarStop);
		this.stepAction1.Activated += new global::System.EventHandler (this.OnToolbarStep);
		this.resumeAction.Activated += new global::System.EventHandler (this.OnToolbarResume);
	}
}
