
// This file has been generated by the GUI designer. Do not modify.
namespace MequantaStudio.SmartQuant
{
	public partial class NewInstrumentDialog
	{
		private global::Gtk.Table tblCommon;
		
		private global::Gtk.ComboBox cbxType;
		
		private global::Gtk.Label label10;
		
		private global::Gtk.Label label11;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.Entry txtExchange;
		
		private global::Gtk.Entry txtSymbol;
		
		private global::Gtk.Table tblCurrency;
		
		private global::Gtk.Label label13;
		
		private global::Gtk.Entry txtCurrency;
		
		private global::Gtk.Table tblMaturity;
		
		private global::Gtk.ComboBoxEntry dtpMaturity;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Table tblOption;
		
		private global::Gtk.ComboBox cbxPutCall;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.SpinButton sbnStrike;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MequantaStudio.SmartQuant.NewInstrumentDialog
			this.Name = "MequantaStudio.SmartQuant.NewInstrumentDialog";
			this.Modal = true;
			this.Resizable = false;
			this.AllowGrow = false;
			// Internal child MequantaStudio.SmartQuant.NewInstrumentDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(3));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.tblCommon = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
			this.tblCommon.Name = "tblCommon";
			this.tblCommon.RowSpacing = ((uint)(2));
			this.tblCommon.ColumnSpacing = ((uint)(6));
			this.tblCommon.BorderWidth = ((uint)(1));
			// Container child tblCommon.Gtk.Table+TableChild
			this.cbxType = global::Gtk.ComboBox.NewText ();
			this.cbxType.Name = "cbxType";
			this.tblCommon.Add (this.cbxType);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.tblCommon [this.cbxType]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			// Container child tblCommon.Gtk.Table+TableChild
			this.label10 = new global::Gtk.Label ();
			this.label10.WidthRequest = 60;
			this.label10.Name = "label10";
			this.label10.Xalign = 0F;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Symbol");
			this.tblCommon.Add (this.label10);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.tblCommon [this.label10]));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child tblCommon.Gtk.Table+TableChild
			this.label11 = new global::Gtk.Label ();
			this.label11.WidthRequest = 60;
			this.label11.Name = "label11";
			this.label11.Xalign = 0F;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Exchange");
			this.tblCommon.Add (this.label11);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.tblCommon [this.label11]));
			w4.TopAttach = ((uint)(2));
			w4.BottomAttach = ((uint)(3));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child tblCommon.Gtk.Table+TableChild
			this.label9 = new global::Gtk.Label ();
			this.label9.WidthRequest = 60;
			this.label9.Name = "label9";
			this.label9.Xalign = 0F;
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Type");
			this.tblCommon.Add (this.label9);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.tblCommon [this.label9]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child tblCommon.Gtk.Table+TableChild
			this.txtExchange = new global::Gtk.Entry ();
			this.txtExchange.CanFocus = true;
			this.txtExchange.Name = "txtExchange";
			this.txtExchange.IsEditable = true;
			this.txtExchange.InvisibleChar = '●';
			this.tblCommon.Add (this.txtExchange);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.tblCommon [this.txtExchange]));
			w6.TopAttach = ((uint)(2));
			w6.BottomAttach = ((uint)(3));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			// Container child tblCommon.Gtk.Table+TableChild
			this.txtSymbol = new global::Gtk.Entry ();
			this.txtSymbol.CanFocus = true;
			this.txtSymbol.Name = "txtSymbol";
			this.txtSymbol.IsEditable = true;
			this.txtSymbol.InvisibleChar = '●';
			this.tblCommon.Add (this.txtSymbol);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.tblCommon [this.txtSymbol]));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.YOptions = ((global::Gtk.AttachOptions)(0));
			w1.Add (this.tblCommon);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(w1 [this.tblCommon]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.tblCurrency = new global::Gtk.Table (((uint)(1)), ((uint)(2)), false);
			this.tblCurrency.Name = "tblCurrency";
			this.tblCurrency.RowSpacing = ((uint)(2));
			this.tblCurrency.ColumnSpacing = ((uint)(6));
			this.tblCurrency.BorderWidth = ((uint)(1));
			// Container child tblCurrency.Gtk.Table+TableChild
			this.label13 = new global::Gtk.Label ();
			this.label13.WidthRequest = 60;
			this.label13.Name = "label13";
			this.label13.Xalign = 0F;
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Currency");
			this.tblCurrency.Add (this.label13);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.tblCurrency [this.label13]));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child tblCurrency.Gtk.Table+TableChild
			this.txtCurrency = new global::Gtk.Entry ();
			this.txtCurrency.CanFocus = true;
			this.txtCurrency.Name = "txtCurrency";
			this.txtCurrency.IsEditable = true;
			this.txtCurrency.InvisibleChar = '●';
			this.tblCurrency.Add (this.txtCurrency);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.tblCurrency [this.txtCurrency]));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.YOptions = ((global::Gtk.AttachOptions)(0));
			w1.Add (this.tblCurrency);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(w1 [this.tblCurrency]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.tblMaturity = new global::Gtk.Table (((uint)(1)), ((uint)(2)), false);
			this.tblMaturity.Name = "tblMaturity";
			this.tblMaturity.RowSpacing = ((uint)(2));
			this.tblMaturity.ColumnSpacing = ((uint)(6));
			this.tblMaturity.BorderWidth = ((uint)(1));
			// Container child tblMaturity.Gtk.Table+TableChild
			this.dtpMaturity = global::Gtk.ComboBoxEntry.NewText ();
			this.dtpMaturity.Name = "dtpMaturity";
			this.dtpMaturity.HasFrame = false;
			this.tblMaturity.Add (this.dtpMaturity);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.tblMaturity [this.dtpMaturity]));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblMaturity.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.WidthRequest = 60;
			this.label1.Name = "label1";
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Maturity");
			this.tblMaturity.Add (this.label1);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.tblMaturity [this.label1]));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(0));
			w1.Add (this.tblMaturity);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(w1 [this.tblMaturity]));
			w14.Position = 2;
			w14.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.tblOption = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.tblOption.Name = "tblOption";
			this.tblOption.RowSpacing = ((uint)(2));
			this.tblOption.ColumnSpacing = ((uint)(6));
			this.tblOption.BorderWidth = ((uint)(1));
			// Container child tblOption.Gtk.Table+TableChild
			this.cbxPutCall = global::Gtk.ComboBox.NewText ();
			this.cbxPutCall.Name = "cbxPutCall";
			this.tblOption.Add (this.cbxPutCall);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.tblOption [this.cbxPutCall]));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tblOption.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.WidthRequest = 60;
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("PutCall");
			this.tblOption.Add (this.label2);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.tblOption [this.label2]));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child tblOption.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.WidthRequest = 60;
			this.label4.Name = "label4";
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Strike");
			this.tblOption.Add (this.label4);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.tblOption [this.label4]));
			w17.TopAttach = ((uint)(1));
			w17.BottomAttach = ((uint)(2));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(0));
			// Container child tblOption.Gtk.Table+TableChild
			this.sbnStrike = new global::Gtk.SpinButton (0, 100, 1);
			this.sbnStrike.CanFocus = true;
			this.sbnStrike.Name = "sbnStrike";
			this.sbnStrike.Adjustment.PageIncrement = 10;
			this.sbnStrike.ClimbRate = 1;
			this.sbnStrike.Digits = ((uint)(4));
			this.sbnStrike.Numeric = true;
			this.tblOption.Add (this.sbnStrike);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.tblOption [this.sbnStrike]));
			w18.TopAttach = ((uint)(1));
			w18.BottomAttach = ((uint)(2));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			w1.Add (this.tblOption);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(w1 [this.tblOption]));
			w19.Position = 3;
			w19.Expand = false;
			w19.Fill = false;
			// Internal child MequantaStudio.SmartQuant.NewInstrumentDialog.ActionArea
			global::Gtk.HButtonBox w20 = this.ActionArea;
			w20.Name = "dialog1_ActionArea";
			w20.Spacing = 10;
			w20.BorderWidth = ((uint)(5));
			w20.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w21 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w20 [this.buttonCancel]));
			w21.Expand = false;
			w21.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w22 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w20 [this.buttonOk]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 276;
			this.DefaultHeight = 302;
			this.Show ();
		}
	}
}
