
// This file has been generated by the GUI designer. Do not modify.
namespace MequantaStudio.SmartQuant
{
	public partial class ImportWizardStep1Widget
	{
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView tvFiles;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.VButtonBox vbuttonbox2;
		
		private global::Gtk.Button btnAddFile;
		
		private global::Gtk.Button btnAddDirectory;
		
		private global::Gtk.Button btnRemove;
		
		private global::Gtk.Label label1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MequantaStudio.SmartQuant.ImportWizardStep1Widget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MequantaStudio.SmartQuant.ImportWizardStep1Widget";
			// Container child MequantaStudio.SmartQuant.ImportWizardStep1Widget.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tvFiles = new global::Gtk.TreeView ();
			this.tvFiles.CanFocus = true;
			this.tvFiles.Name = "tvFiles";
			this.GtkScrolledWindow.Add (this.tvFiles);
			this.hbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.GtkScrolledWindow]));
			w2.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbuttonbox2 = new global::Gtk.VButtonBox ();
			this.vbuttonbox2.Name = "vbuttonbox2";
			this.vbuttonbox2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.btnAddFile = new global::Gtk.Button ();
			this.btnAddFile.CanFocus = true;
			this.btnAddFile.Name = "btnAddFile";
			this.btnAddFile.UseUnderline = true;
			this.btnAddFile.Label = global::Mono.Unix.Catalog.GetString ("Add File...");
			this.vbuttonbox2.Add (this.btnAddFile);
			global::Gtk.ButtonBox.ButtonBoxChild w3 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2 [this.btnAddFile]));
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.btnAddDirectory = new global::Gtk.Button ();
			this.btnAddDirectory.CanFocus = true;
			this.btnAddDirectory.Name = "btnAddDirectory";
			this.btnAddDirectory.UseUnderline = true;
			this.btnAddDirectory.Label = global::Mono.Unix.Catalog.GetString ("Add Directory...");
			this.vbuttonbox2.Add (this.btnAddDirectory);
			global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2 [this.btnAddDirectory]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.btnRemove = new global::Gtk.Button ();
			this.btnRemove.CanFocus = true;
			this.btnRemove.Name = "btnRemove";
			this.btnRemove.UseUnderline = true;
			this.btnRemove.Label = global::Mono.Unix.Catalog.GetString ("Remove");
			this.vbuttonbox2.Add (this.btnRemove);
			global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2 [this.btnRemove]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox1.Add (this.vbuttonbox2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbuttonbox2]));
			w6.Position = 0;
			w6.Expand = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Note:\nIf you selection more \nthan one file make \nsure that all files have \nthe same format!");
			this.label1.Wrap = true;
			this.vbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.label1]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.hbox1.Add (this.vbox1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox1]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.btnAddFile.Clicked += new global::System.EventHandler (this.OnAddFileClicked);
			this.btnAddDirectory.Clicked += new global::System.EventHandler (this.OnAddDirectoryClicked);
			this.btnRemove.Clicked += new global::System.EventHandler (this.OnRemoveClicked);
		}
	}
}
