
// This file has been generated by the GUI designer. Do not modify.
namespace MequantaStudio.SmartQuant
{
	public partial class PortfolioWidget
	{
		private global::Gtk.Notebook notebook4;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.Frame frame1;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView treeview9;
		
		private global::Gtk.Label GtkLabel;
		
		private global::Gtk.Frame frame2;
		
		private global::Gtk.Alignment GtkAlignment1;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		
		private global::Gtk.TreeView treeview10;
		
		private global::Gtk.Label GtkLabel1;
		
		private global::Gtk.Frame frame3;
		
		private global::Gtk.Alignment GtkAlignment2;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		
		private global::Gtk.TreeView treeview11;
		
		private global::Gtk.Label GtkLabel2;
		
		private global::Gtk.Label label10;
		
		private global::Gtk.Label label11;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow4;
		
		private global::Gtk.TreeView treeview13;
		
		private global::Gtk.Notebook notebook5;
		
		private global::Gtk.Label label15;
		
		private global::Gtk.Label label16;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow3;
		
		private global::Gtk.TreeView treeview12;
		
		private global::Gtk.Label label17;
		
		private global::Gtk.Label label12;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow5;
		
		private global::Gtk.TreeView treeview14;
		
		private global::Gtk.Label label13;
		
		private global::Gtk.VBox vbox5;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Label label18;
		
		private global::Gtk.ComboBox combobox2;
		
		private global::Gtk.Label label14;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MequantaStudio.SmartQuant.PortfolioWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MequantaStudio.SmartQuant.PortfolioWidget";
			// Container child MequantaStudio.SmartQuant.PortfolioWidget.Gtk.Container+ContainerChild
			this.notebook4 = new global::Gtk.Notebook ();
			this.notebook4.CanFocus = true;
			this.notebook4.Name = "notebook4";
			this.notebook4.CurrentPage = 4;
			// Container child notebook4.Gtk.Notebook+NotebookChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview9 = new global::Gtk.TreeView ();
			this.treeview9.CanFocus = true;
			this.treeview9.Name = "treeview9";
			this.GtkScrolledWindow.Add (this.treeview9);
			this.GtkAlignment.Add (this.GtkScrolledWindow);
			this.frame1.Add (this.GtkAlignment);
			this.GtkLabel = new global::Gtk.Label ();
			this.GtkLabel.Name = "GtkLabel";
			this.GtkLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Positions</b>");
			this.GtkLabel.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel;
			this.vbox3.Add (this.frame1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.frame1]));
			w4.Position = 0;
			w4.Expand = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.treeview10 = new global::Gtk.TreeView ();
			this.treeview10.CanFocus = true;
			this.treeview10.Name = "treeview10";
			this.GtkScrolledWindow1.Add (this.treeview10);
			this.GtkAlignment1.Add (this.GtkScrolledWindow1);
			this.frame2.Add (this.GtkAlignment1);
			this.GtkLabel1 = new global::Gtk.Label ();
			this.GtkLabel1.Name = "GtkLabel1";
			this.GtkLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Transactions</b>");
			this.GtkLabel1.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel1;
			this.vbox3.Add (this.frame2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.frame2]));
			w8.Position = 1;
			// Container child vbox3.Gtk.Box+BoxChild
			this.frame3 = new global::Gtk.Frame ();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.treeview11 = new global::Gtk.TreeView ();
			this.treeview11.CanFocus = true;
			this.treeview11.Name = "treeview11";
			this.GtkScrolledWindow2.Add (this.treeview11);
			this.GtkAlignment2.Add (this.GtkScrolledWindow2);
			this.frame3.Add (this.GtkAlignment2);
			this.GtkLabel2 = new global::Gtk.Label ();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Value</b>");
			this.GtkLabel2.UseMarkup = true;
			this.frame3.LabelWidget = this.GtkLabel2;
			this.vbox3.Add (this.frame3);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.frame3]));
			w12.Position = 2;
			w12.Expand = false;
			this.notebook4.Add (this.vbox3);
			// Notebook tab
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Composition");
			this.notebook4.SetTabLabel (this.vbox3, this.label10);
			this.label10.ShowAll ();
			// Notebook tab
			global::Gtk.Label w14 = new global::Gtk.Label ();
			w14.Visible = true;
			this.notebook4.Add (w14);
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Performance");
			this.notebook4.SetTabLabel (w14, this.label11);
			this.label11.ShowAll ();
			// Container child notebook4.Gtk.Notebook+NotebookChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow4 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow4.Name = "GtkScrolledWindow4";
			this.GtkScrolledWindow4.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow4.Gtk.Container+ContainerChild
			this.treeview13 = new global::Gtk.TreeView ();
			this.treeview13.CanFocus = true;
			this.treeview13.Name = "treeview13";
			this.GtkScrolledWindow4.Add (this.treeview13);
			this.vbox4.Add (this.GtkScrolledWindow4);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.GtkScrolledWindow4]));
			w16.Position = 0;
			// Container child vbox4.Gtk.Box+BoxChild
			this.notebook5 = new global::Gtk.Notebook ();
			this.notebook5.CanFocus = true;
			this.notebook5.Name = "notebook5";
			this.notebook5.CurrentPage = 0;
			// Notebook tab
			global::Gtk.Label w17 = new global::Gtk.Label ();
			w17.Visible = true;
			this.notebook5.Add (w17);
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Chart");
			this.notebook5.SetTabLabel (w17, this.label15);
			this.label15.ShowAll ();
			// Notebook tab
			global::Gtk.Label w18 = new global::Gtk.Label ();
			w18.Visible = true;
			this.notebook5.Add (w18);
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Histogram");
			this.notebook5.SetTabLabel (w18, this.label16);
			this.label16.ShowAll ();
			// Container child notebook5.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
			this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
			this.treeview12 = new global::Gtk.TreeView ();
			this.treeview12.CanFocus = true;
			this.treeview12.Name = "treeview12";
			this.GtkScrolledWindow3.Add (this.treeview12);
			this.notebook5.Add (this.GtkScrolledWindow3);
			global::Gtk.Notebook.NotebookChild w20 = ((global::Gtk.Notebook.NotebookChild)(this.notebook5 [this.GtkScrolledWindow3]));
			w20.Position = 2;
			// Notebook tab
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("Data");
			this.notebook5.SetTabLabel (this.GtkScrolledWindow3, this.label17);
			this.label17.ShowAll ();
			this.vbox4.Add (this.notebook5);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.notebook5]));
			w21.Position = 1;
			w21.Expand = false;
			this.notebook4.Add (this.vbox4);
			global::Gtk.Notebook.NotebookChild w22 = ((global::Gtk.Notebook.NotebookChild)(this.notebook4 [this.vbox4]));
			w22.Position = 2;
			// Notebook tab
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Statistics");
			this.notebook4.SetTabLabel (this.vbox4, this.label12);
			this.label12.ShowAll ();
			// Container child notebook4.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow5 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow5.Name = "GtkScrolledWindow5";
			this.GtkScrolledWindow5.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow5.Gtk.Container+ContainerChild
			this.treeview14 = new global::Gtk.TreeView ();
			this.treeview14.CanFocus = true;
			this.treeview14.Name = "treeview14";
			this.GtkScrolledWindow5.Add (this.treeview14);
			this.notebook4.Add (this.GtkScrolledWindow5);
			global::Gtk.Notebook.NotebookChild w24 = ((global::Gtk.Notebook.NotebookChild)(this.notebook4 [this.GtkScrolledWindow5]));
			w24.Position = 3;
			// Notebook tab
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Children Statistics");
			this.notebook4.SetTabLabel (this.GtkScrolledWindow5, this.label13);
			this.label13.ShowAll ();
			// Container child notebook4.Gtk.Notebook+NotebookChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Choose Statistics:");
			this.hbox1.Add (this.label18);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label18]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.combobox2 = global::Gtk.ComboBox.NewText ();
			this.combobox2.Name = "combobox2";
			this.hbox1.Add (this.combobox2);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.combobox2]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			this.vbox5.Add (this.hbox1);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox1]));
			w27.Position = 0;
			w27.Expand = false;
			w27.Fill = false;
			this.notebook4.Add (this.vbox5);
			global::Gtk.Notebook.NotebookChild w28 = ((global::Gtk.Notebook.NotebookChild)(this.notebook4 [this.vbox5]));
			w28.Position = 4;
			// Notebook tab
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Correlation Matrix");
			this.notebook4.SetTabLabel (this.vbox5, this.label14);
			this.label14.ShowAll ();
			this.Add (this.notebook4);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
