
// This file has been generated by the GUI designer. Do not modify.
namespace MequantaStudio.SmartQuant
{
	public partial class OrderManagerWidget
	{
		private global::Gtk.VPaned vpaned2;
		
		private global::Gtk.Notebook notebook3;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		
		private global::Gtk.TreeView treeview4;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		
		private global::Gtk.TreeView treeview5;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow3;
		
		private global::Gtk.TreeView treeview6;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow4;
		
		private global::Gtk.TreeView treeview7;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow5;
		
		private global::Gtk.TreeView treeview8;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.Notebook notebook2;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView treeview3;
		
		private global::Gtk.Label label4;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MequantaStudio.SmartQuant.OrderManagerWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MequantaStudio.SmartQuant.OrderManagerWidget";
			// Container child MequantaStudio.SmartQuant.OrderManagerWidget.Gtk.Container+ContainerChild
			this.vpaned2 = new global::Gtk.VPaned ();
			this.vpaned2.CanFocus = true;
			this.vpaned2.Name = "vpaned2";
			this.vpaned2.Position = 334;
			// Container child vpaned2.Gtk.Paned+PanedChild
			this.notebook3 = new global::Gtk.Notebook ();
			this.notebook3.CanFocus = true;
			this.notebook3.Name = "notebook3";
			this.notebook3.CurrentPage = 4;
			// Container child notebook3.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.treeview4 = new global::Gtk.TreeView ();
			this.treeview4.CanFocus = true;
			this.treeview4.Name = "treeview4";
			this.GtkScrolledWindow1.Add (this.treeview4);
			this.notebook3.Add (this.GtkScrolledWindow1);
			// Notebook tab
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("All");
			this.notebook3.SetTabLabel (this.GtkScrolledWindow1, this.label5);
			this.label5.ShowAll ();
			// Container child notebook3.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.treeview5 = new global::Gtk.TreeView ();
			this.treeview5.CanFocus = true;
			this.treeview5.Name = "treeview5";
			this.GtkScrolledWindow2.Add (this.treeview5);
			this.notebook3.Add (this.GtkScrolledWindow2);
			global::Gtk.Notebook.NotebookChild w4 = ((global::Gtk.Notebook.NotebookChild)(this.notebook3 [this.GtkScrolledWindow2]));
			w4.Position = 1;
			// Notebook tab
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Working");
			this.notebook3.SetTabLabel (this.GtkScrolledWindow2, this.label6);
			this.label6.ShowAll ();
			// Container child notebook3.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
			this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
			this.treeview6 = new global::Gtk.TreeView ();
			this.treeview6.CanFocus = true;
			this.treeview6.Name = "treeview6";
			this.GtkScrolledWindow3.Add (this.treeview6);
			this.notebook3.Add (this.GtkScrolledWindow3);
			global::Gtk.Notebook.NotebookChild w6 = ((global::Gtk.Notebook.NotebookChild)(this.notebook3 [this.GtkScrolledWindow3]));
			w6.Position = 2;
			// Notebook tab
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Filled");
			this.notebook3.SetTabLabel (this.GtkScrolledWindow3, this.label7);
			this.label7.ShowAll ();
			// Container child notebook3.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow4 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow4.Name = "GtkScrolledWindow4";
			this.GtkScrolledWindow4.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow4.Gtk.Container+ContainerChild
			this.treeview7 = new global::Gtk.TreeView ();
			this.treeview7.CanFocus = true;
			this.treeview7.Name = "treeview7";
			this.GtkScrolledWindow4.Add (this.treeview7);
			this.notebook3.Add (this.GtkScrolledWindow4);
			global::Gtk.Notebook.NotebookChild w8 = ((global::Gtk.Notebook.NotebookChild)(this.notebook3 [this.GtkScrolledWindow4]));
			w8.Position = 3;
			// Notebook tab
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Cancelled");
			this.notebook3.SetTabLabel (this.GtkScrolledWindow4, this.label8);
			this.label8.ShowAll ();
			// Container child notebook3.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow5 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow5.Name = "GtkScrolledWindow5";
			this.GtkScrolledWindow5.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow5.Gtk.Container+ContainerChild
			this.treeview8 = new global::Gtk.TreeView ();
			this.treeview8.CanFocus = true;
			this.treeview8.Name = "treeview8";
			this.GtkScrolledWindow5.Add (this.treeview8);
			this.notebook3.Add (this.GtkScrolledWindow5);
			global::Gtk.Notebook.NotebookChild w10 = ((global::Gtk.Notebook.NotebookChild)(this.notebook3 [this.GtkScrolledWindow5]));
			w10.Position = 4;
			// Notebook tab
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Rejected");
			this.notebook3.SetTabLabel (this.GtkScrolledWindow5, this.label9);
			this.label9.ShowAll ();
			this.vpaned2.Add (this.notebook3);
			global::Gtk.Paned.PanedChild w11 = ((global::Gtk.Paned.PanedChild)(this.vpaned2 [this.notebook3]));
			w11.Resize = false;
			// Container child vpaned2.Gtk.Paned+PanedChild
			this.notebook2 = new global::Gtk.Notebook ();
			this.notebook2.CanFocus = true;
			this.notebook2.Name = "notebook2";
			this.notebook2.CurrentPage = 0;
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview3 = new global::Gtk.TreeView ();
			this.treeview3.CanFocus = true;
			this.treeview3.Name = "treeview3";
			this.GtkScrolledWindow.Add (this.treeview3);
			this.notebook2.Add (this.GtkScrolledWindow);
			// Notebook tab
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Reports");
			this.notebook2.SetTabLabel (this.GtkScrolledWindow, this.label4);
			this.label4.ShowAll ();
			this.vpaned2.Add (this.notebook2);
			this.Add (this.vpaned2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
