
// This file has been generated by the GUI designer. Do not modify.
namespace MequantaStudio.SmartQuant
{
	public partial class ImportWizardStep2Widget
	{
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.Notebook notebook2;
		
		private global::Gtk.Table table1;
		
		private global::Gtk.Frame frame5;
		
		private global::Gtk.Alignment GtkAlignment;
		
		private global::Gtk.Table table2;
		
		private global::Gtk.ComboBox combobox2;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.SpinButton spinbutton1;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Label GtkLabel8;
		
		private global::Gtk.Frame frame6;
		
		private global::Gtk.Alignment GtkAlignment1;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.ComboBox combobox3;
		
		private global::Gtk.Table table3;
		
		private global::Gtk.ComboBox combobox4;
		
		private global::Gtk.Label label10;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.SpinButton spinbutton2;
		
		private global::Gtk.Label GtkLabel7;
		
		private global::Gtk.Frame frame7;
		
		private global::Gtk.Alignment GtkAlignment2;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.RadioButton radiobutton4;
		
		private global::Gtk.RadioButton radiobutton5;
		
		private global::Gtk.ComboBox combobox5;
		
		private global::Gtk.Label GtkLabel5;
		
		private global::Gtk.Frame frame8;
		
		private global::Gtk.Alignment GtkAlignment3;
		
		private global::Gtk.Table table4;
		
		private global::Gtk.Entry entry1;
		
		private global::Gtk.RadioButton radiobutton1;
		
		private global::Gtk.RadioButton radiobutton2;
		
		private global::Gtk.RadioButton radiobutton3;
		
		private global::Gtk.Label GtkLabel6;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Table table5;
		
		private global::Gtk.Frame frame10;
		
		private global::Gtk.Alignment GtkAlignment5;
		
		private global::Gtk.VBox vbox5;
		
		private global::Gtk.HBox hbox7;
		
		private global::Gtk.CheckButton checkbutton1;
		
		private global::Gtk.ComboBox combobox7;
		
		private global::Gtk.CheckButton checkbutton2;
		
		private global::Gtk.CheckButton checkbutton3;
		
		private global::Gtk.Label GtkLabel13;
		
		private global::Gtk.Frame frame11;
		
		private global::Gtk.Alignment GtkAlignment6;
		
		private global::Gtk.VBox vbox6;
		
		private global::Gtk.CheckButton checkbutton4;
		
		private global::Gtk.Table table6;
		
		private global::Gtk.ComboBox combobox8;
		
		private global::Gtk.ComboBox combobox9;
		
		private global::Gtk.Label label12;
		
		private global::Gtk.Label label13;
		
		private global::Gtk.Label GtkLabel14;
		
		private global::Gtk.Frame frame9;
		
		private global::Gtk.Alignment GtkAlignment4;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.Label label11;
		
		private global::Gtk.ComboBox combobox6;
		
		private global::Gtk.Label GtkLabel9;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.ToggleButton togglebutton4;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView textview1;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.ComboBox combobox1;
		
		private global::Gtk.Button button7;
		
		private global::Gtk.Button button8;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.Image image3;
		
		private global::Gtk.Label label9;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MequantaStudio.SmartQuant.ImportWizardStep2Widget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MequantaStudio.SmartQuant.ImportWizardStep2Widget";
			// Container child MequantaStudio.SmartQuant.ImportWizardStep2Widget.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.notebook2 = new global::Gtk.Notebook ();
			this.notebook2.CanFocus = true;
			this.notebook2.Name = "notebook2";
			this.notebook2.CurrentPage = 1;
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.table1 = new global::Gtk.Table (((uint)(1)), ((uint)(4)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.frame5 = new global::Gtk.Frame ();
			this.frame5.Name = "frame5";
			this.frame5.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame5.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.table2 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.combobox2 = global::Gtk.ComboBox.NewText ();
			this.combobox2.Name = "combobox2";
			this.table2.Add (this.combobox2);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table2 [this.combobox2]));
			w1.LeftAttach = ((uint)(1));
			w1.RightAttach = ((uint)(2));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.spinbutton1 = new global::Gtk.SpinButton (0, 100, 1);
			this.spinbutton1.CanFocus = true;
			this.spinbutton1.Name = "spinbutton1";
			this.spinbutton1.Adjustment.PageIncrement = 10;
			this.spinbutton1.ClimbRate = 1;
			this.spinbutton1.Numeric = true;
			this.hbox4.Add (this.spinbutton1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.spinbutton1]));
			w2.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("lines");
			this.hbox4.Add (this.label3);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label3]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.table2.Add (this.hbox4);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2 [this.hbox4]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Separator");
			this.table2.Add (this.label1);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table2 [this.label1]));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Header with");
			this.table2.Add (this.label2);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table2 [this.label2]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment.Add (this.table2);
			this.frame5.Add (this.GtkAlignment);
			this.GtkLabel8 = new global::Gtk.Label ();
			this.GtkLabel8.Name = "GtkLabel8";
			this.GtkLabel8.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>CSV</b>");
			this.GtkLabel8.UseMarkup = true;
			this.frame5.LabelWidget = this.GtkLabel8;
			this.table1.Add (this.frame5);
			// Container child table1.Gtk.Table+TableChild
			this.frame6 = new global::Gtk.Frame ();
			this.frame6.Name = "frame6";
			this.frame6.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame6.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Type");
			this.hbox5.Add (this.label7);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label7]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.combobox3 = global::Gtk.ComboBox.NewText ();
			this.combobox3.Name = "combobox3";
			this.hbox5.Add (this.combobox3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.combobox3]));
			w11.Position = 1;
			this.vbox1.Add (this.hbox5);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox5]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.table3 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.combobox4 = global::Gtk.ComboBox.NewText ();
			this.combobox4.Name = "combobox4";
			this.table3.Add (this.combobox4);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table3 [this.combobox4]));
			w13.TopAttach = ((uint)(1));
			w13.BottomAttach = ((uint)(2));
			w13.LeftAttach = ((uint)(1));
			w13.RightAttach = ((uint)(2));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Bar datetime");
			this.table3.Add (this.label10);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table3 [this.label10]));
			w14.TopAttach = ((uint)(1));
			w14.BottomAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Bar size(sec)");
			this.table3.Add (this.label8);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table3 [this.label8]));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.spinbutton2 = new global::Gtk.SpinButton (0, 100, 1);
			this.spinbutton2.CanFocus = true;
			this.spinbutton2.Name = "spinbutton2";
			this.spinbutton2.Adjustment.PageIncrement = 10;
			this.spinbutton2.ClimbRate = 1;
			this.spinbutton2.Numeric = true;
			this.table3.Add (this.spinbutton2);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table3 [this.spinbutton2]));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox1.Add (this.table3);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table3]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			this.GtkAlignment1.Add (this.vbox1);
			this.frame6.Add (this.GtkAlignment1);
			this.GtkLabel7 = new global::Gtk.Label ();
			this.GtkLabel7.Name = "GtkLabel7";
			this.GtkLabel7.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Data</b>");
			this.GtkLabel7.UseMarkup = true;
			this.frame6.LabelWidget = this.GtkLabel7;
			this.table1.Add (this.frame6);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1 [this.frame6]));
			w20.LeftAttach = ((uint)(1));
			w20.RightAttach = ((uint)(2));
			// Container child table1.Gtk.Table+TableChild
			this.frame7 = new global::Gtk.Frame ();
			this.frame7.Name = "frame7";
			this.frame7.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame7.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.radiobutton4 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("radiobutton4"));
			this.radiobutton4.CanFocus = true;
			this.radiobutton4.Name = "radiobutton4";
			this.radiobutton4.Active = true;
			this.radiobutton4.DrawIndicator = true;
			this.radiobutton4.UseUnderline = true;
			this.radiobutton4.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.vbox2.Add (this.radiobutton4);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.radiobutton4]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.radiobutton5 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("radiobutton5"));
			this.radiobutton5.CanFocus = true;
			this.radiobutton5.Name = "radiobutton5";
			this.radiobutton5.DrawIndicator = true;
			this.radiobutton5.UseUnderline = true;
			this.radiobutton5.Group = this.radiobutton4.Group;
			this.vbox2.Add (this.radiobutton5);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.radiobutton5]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.combobox5 = global::Gtk.ComboBox.NewText ();
			this.combobox5.Name = "combobox5";
			this.vbox2.Add (this.combobox5);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.combobox5]));
			w23.Position = 2;
			w23.Expand = false;
			w23.Fill = false;
			this.GtkAlignment2.Add (this.vbox2);
			this.frame7.Add (this.GtkAlignment2);
			this.GtkLabel5 = new global::Gtk.Label ();
			this.GtkLabel5.Name = "GtkLabel5";
			this.GtkLabel5.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Date</b>");
			this.GtkLabel5.UseMarkup = true;
			this.frame7.LabelWidget = this.GtkLabel5;
			this.table1.Add (this.frame7);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table1 [this.frame7]));
			w26.LeftAttach = ((uint)(2));
			w26.RightAttach = ((uint)(3));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.frame8 = new global::Gtk.Frame ();
			this.frame8.Name = "frame8";
			this.frame8.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame8.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.table4 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
			this.table4.Name = "table4";
			this.table4.RowSpacing = ((uint)(6));
			this.table4.ColumnSpacing = ((uint)(6));
			// Container child table4.Gtk.Table+TableChild
			this.entry1 = new global::Gtk.Entry ();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '●';
			this.table4.Add (this.entry1);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table4 [this.entry1]));
			w27.TopAttach = ((uint)(2));
			w27.BottomAttach = ((uint)(3));
			w27.LeftAttach = ((uint)(1));
			w27.RightAttach = ((uint)(2));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.radiobutton1 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("collumn"));
			this.radiobutton1.CanFocus = true;
			this.radiobutton1.Name = "radiobutton1";
			this.radiobutton1.DrawIndicator = true;
			this.radiobutton1.UseUnderline = true;
			this.radiobutton1.Group = this.radiobutton4.Group;
			this.table4.Add (this.radiobutton1);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table4 [this.radiobutton1]));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.radiobutton2 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("file name"));
			this.radiobutton2.CanFocus = true;
			this.radiobutton2.Name = "radiobutton2";
			this.radiobutton2.DrawIndicator = true;
			this.radiobutton2.UseUnderline = true;
			this.radiobutton2.Group = this.radiobutton4.Group;
			this.table4.Add (this.radiobutton2);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table4 [this.radiobutton2]));
			w29.TopAttach = ((uint)(1));
			w29.BottomAttach = ((uint)(2));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table4.Gtk.Table+TableChild
			this.radiobutton3 = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("manually"));
			this.radiobutton3.CanFocus = true;
			this.radiobutton3.Name = "radiobutton3";
			this.radiobutton3.DrawIndicator = true;
			this.radiobutton3.UseUnderline = true;
			this.radiobutton3.Group = this.radiobutton4.Group;
			this.table4.Add (this.radiobutton3);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table4 [this.radiobutton3]));
			w30.TopAttach = ((uint)(2));
			w30.BottomAttach = ((uint)(3));
			w30.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment3.Add (this.table4);
			this.frame8.Add (this.GtkAlignment3);
			this.GtkLabel6 = new global::Gtk.Label ();
			this.GtkLabel6.Name = "GtkLabel6";
			this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Symbol</b>");
			this.GtkLabel6.UseMarkup = true;
			this.frame8.LabelWidget = this.GtkLabel6;
			this.table1.Add (this.frame8);
			global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table1 [this.frame8]));
			w33.LeftAttach = ((uint)(3));
			w33.RightAttach = ((uint)(4));
			w33.YOptions = ((global::Gtk.AttachOptions)(4));
			this.notebook2.Add (this.table1);
			// Notebook tab
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Options");
			this.notebook2.SetTabLabel (this.table1, this.label4);
			this.label4.ShowAll ();
			// Container child notebook2.Gtk.Notebook+NotebookChild
			this.table5 = new global::Gtk.Table (((uint)(1)), ((uint)(3)), false);
			this.table5.Name = "table5";
			this.table5.RowSpacing = ((uint)(6));
			this.table5.ColumnSpacing = ((uint)(6));
			// Container child table5.Gtk.Table+TableChild
			this.frame10 = new global::Gtk.Frame ();
			this.frame10.Name = "frame10";
			this.frame10.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame10.Gtk.Container+ContainerChild
			this.GtkAlignment5 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment5.Name = "GtkAlignment5";
			this.GtkAlignment5.LeftPadding = ((uint)(12));
			// Container child GtkAlignment5.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.checkbutton1 = new global::Gtk.CheckButton ();
			this.checkbutton1.CanFocus = true;
			this.checkbutton1.Name = "checkbutton1";
			this.checkbutton1.Label = global::Mono.Unix.Catalog.GetString ("Create instrument");
			this.checkbutton1.DrawIndicator = true;
			this.checkbutton1.UseUnderline = true;
			this.hbox7.Add (this.checkbutton1);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.checkbutton1]));
			w35.Position = 0;
			// Container child hbox7.Gtk.Box+BoxChild
			this.combobox7 = global::Gtk.ComboBox.NewText ();
			this.combobox7.Name = "combobox7";
			this.hbox7.Add (this.combobox7);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.combobox7]));
			w36.Position = 1;
			this.vbox5.Add (this.hbox7);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox7]));
			w37.Position = 0;
			w37.Expand = false;
			w37.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.checkbutton2 = new global::Gtk.CheckButton ();
			this.checkbutton2.CanFocus = true;
			this.checkbutton2.Name = "checkbutton2";
			this.checkbutton2.Label = global::Mono.Unix.Catalog.GetString ("Clear series");
			this.checkbutton2.DrawIndicator = true;
			this.checkbutton2.UseUnderline = true;
			this.vbox5.Add (this.checkbutton2);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.checkbutton2]));
			w38.Position = 1;
			w38.Expand = false;
			w38.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.checkbutton3 = new global::Gtk.CheckButton ();
			this.checkbutton3.CanFocus = true;
			this.checkbutton3.Name = "checkbutton3";
			this.checkbutton3.Label = global::Mono.Unix.Catalog.GetString ("Skip data inside the eisting data time range");
			this.checkbutton3.DrawIndicator = true;
			this.checkbutton3.UseUnderline = true;
			this.vbox5.Add (this.checkbutton3);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.checkbutton3]));
			w39.Position = 2;
			w39.Expand = false;
			w39.Fill = false;
			this.GtkAlignment5.Add (this.vbox5);
			this.frame10.Add (this.GtkAlignment5);
			this.GtkLabel13 = new global::Gtk.Label ();
			this.GtkLabel13.Name = "GtkLabel13";
			this.GtkLabel13.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Other</b>");
			this.GtkLabel13.UseMarkup = true;
			this.frame10.LabelWidget = this.GtkLabel13;
			this.table5.Add (this.frame10);
			global::Gtk.Table.TableChild w42 = ((global::Gtk.Table.TableChild)(this.table5 [this.frame10]));
			w42.LeftAttach = ((uint)(1));
			w42.RightAttach = ((uint)(2));
			w42.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.frame11 = new global::Gtk.Frame ();
			this.frame11.Name = "frame11";
			this.frame11.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame11.Gtk.Container+ContainerChild
			this.GtkAlignment6 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment6.Name = "GtkAlignment6";
			this.GtkAlignment6.LeftPadding = ((uint)(12));
			// Container child GtkAlignment6.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.checkbutton4 = new global::Gtk.CheckButton ();
			this.checkbutton4.CanFocus = true;
			this.checkbutton4.Name = "checkbutton4";
			this.checkbutton4.Label = global::Mono.Unix.Catalog.GetString ("Import only data with in the range");
			this.checkbutton4.DrawIndicator = true;
			this.checkbutton4.UseUnderline = true;
			this.vbox6.Add (this.checkbutton4);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.checkbutton4]));
			w43.Position = 0;
			w43.Expand = false;
			w43.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.table6 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.table6.Name = "table6";
			this.table6.RowSpacing = ((uint)(6));
			this.table6.ColumnSpacing = ((uint)(6));
			// Container child table6.Gtk.Table+TableChild
			this.combobox8 = global::Gtk.ComboBox.NewText ();
			this.combobox8.Name = "combobox8";
			this.table6.Add (this.combobox8);
			global::Gtk.Table.TableChild w44 = ((global::Gtk.Table.TableChild)(this.table6 [this.combobox8]));
			w44.LeftAttach = ((uint)(1));
			w44.RightAttach = ((uint)(2));
			w44.XOptions = ((global::Gtk.AttachOptions)(4));
			w44.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.combobox9 = global::Gtk.ComboBox.NewText ();
			this.combobox9.Name = "combobox9";
			this.table6.Add (this.combobox9);
			global::Gtk.Table.TableChild w45 = ((global::Gtk.Table.TableChild)(this.table6 [this.combobox9]));
			w45.TopAttach = ((uint)(1));
			w45.BottomAttach = ((uint)(2));
			w45.LeftAttach = ((uint)(1));
			w45.RightAttach = ((uint)(2));
			w45.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("From");
			this.table6.Add (this.label12);
			global::Gtk.Table.TableChild w46 = ((global::Gtk.Table.TableChild)(this.table6 [this.label12]));
			w46.XOptions = ((global::Gtk.AttachOptions)(4));
			w46.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table6.Gtk.Table+TableChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("To");
			this.table6.Add (this.label13);
			global::Gtk.Table.TableChild w47 = ((global::Gtk.Table.TableChild)(this.table6 [this.label13]));
			w47.TopAttach = ((uint)(1));
			w47.BottomAttach = ((uint)(2));
			w47.XOptions = ((global::Gtk.AttachOptions)(4));
			w47.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox6.Add (this.table6);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.table6]));
			w48.Position = 1;
			w48.Expand = false;
			w48.Fill = false;
			this.GtkAlignment6.Add (this.vbox6);
			this.frame11.Add (this.GtkAlignment6);
			this.GtkLabel14 = new global::Gtk.Label ();
			this.GtkLabel14.Name = "GtkLabel14";
			this.GtkLabel14.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>DateTime Interval</b>");
			this.GtkLabel14.UseMarkup = true;
			this.frame11.LabelWidget = this.GtkLabel14;
			this.table5.Add (this.frame11);
			global::Gtk.Table.TableChild w51 = ((global::Gtk.Table.TableChild)(this.table5 [this.frame11]));
			w51.LeftAttach = ((uint)(2));
			w51.RightAttach = ((uint)(3));
			w51.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table5.Gtk.Table+TableChild
			this.frame9 = new global::Gtk.Frame ();
			this.frame9.Name = "frame9";
			this.frame9.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame9.Gtk.Container+ContainerChild
			this.GtkAlignment4 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment4.Name = "GtkAlignment4";
			this.GtkAlignment4.LeftPadding = ((uint)(12));
			// Container child GtkAlignment4.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.Xalign = 0F;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Localization");
			this.vbox4.Add (this.label11);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label11]));
			w52.Position = 0;
			w52.Expand = false;
			w52.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.combobox6 = global::Gtk.ComboBox.NewText ();
			this.combobox6.Name = "combobox6";
			this.vbox4.Add (this.combobox6);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.combobox6]));
			w53.Position = 1;
			w53.Expand = false;
			w53.Fill = false;
			this.GtkAlignment4.Add (this.vbox4);
			this.frame9.Add (this.GtkAlignment4);
			this.GtkLabel9 = new global::Gtk.Label ();
			this.GtkLabel9.Name = "GtkLabel9";
			this.GtkLabel9.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>CSV</b>");
			this.GtkLabel9.UseMarkup = true;
			this.frame9.LabelWidget = this.GtkLabel9;
			this.table5.Add (this.frame9);
			this.notebook2.Add (this.table5);
			global::Gtk.Notebook.NotebookChild w57 = ((global::Gtk.Notebook.NotebookChild)(this.notebook2 [this.table5]));
			w57.Position = 1;
			// Notebook tab
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Advanced");
			this.notebook2.SetTabLabel (this.table5, this.label5);
			this.label5.ShowAll ();
			this.vbox3.Add (this.notebook2);
			global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.notebook2]));
			w58.Position = 0;
			w58.Expand = false;
			w58.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.togglebutton4 = new global::Gtk.ToggleButton ();
			this.togglebutton4.CanFocus = true;
			this.togglebutton4.Name = "togglebutton4";
			this.togglebutton4.UseUnderline = true;
			this.togglebutton4.Label = global::Mono.Unix.Catalog.GetString ("GtkToggleButton");
			this.hbox2.Add (this.togglebutton4);
			global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.togglebutton4]));
			w59.Position = 0;
			w59.Expand = false;
			w59.Fill = false;
			this.vbox3.Add (this.hbox2);
			global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
			w60.Position = 1;
			w60.Expand = false;
			w60.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textview1 = new global::Gtk.TextView ();
			this.textview1.CanFocus = true;
			this.textview1.Name = "textview1";
			this.GtkScrolledWindow.Add (this.textview1);
			this.vbox3.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow]));
			w62.Position = 2;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Template");
			this.hbox3.Add (this.label6);
			global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label6]));
			w63.Position = 0;
			w63.Expand = false;
			w63.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.combobox1 = global::Gtk.ComboBox.NewText ();
			this.combobox1.Name = "combobox1";
			this.hbox3.Add (this.combobox1);
			global::Gtk.Box.BoxChild w64 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.combobox1]));
			w64.Position = 1;
			w64.Expand = false;
			w64.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.button7 = new global::Gtk.Button ();
			this.button7.CanFocus = true;
			this.button7.Name = "button7";
			this.button7.UseUnderline = true;
			this.button7.Label = global::Mono.Unix.Catalog.GetString ("Apply");
			this.hbox3.Add (this.button7);
			global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button7]));
			w65.Position = 2;
			w65.Expand = false;
			w65.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.button8 = new global::Gtk.Button ();
			this.button8.CanFocus = true;
			this.button8.Name = "button8";
			this.button8.UseUnderline = true;
			this.button8.Label = global::Mono.Unix.Catalog.GetString ("Save As...");
			this.hbox3.Add (this.button8);
			global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button8]));
			w66.Position = 3;
			w66.Expand = false;
			w66.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.image3 = new global::Gtk.Image ();
			this.image3.Name = "image3";
			this.image3.Xalign = 1F;
			this.hbox6.Add (this.image3);
			global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.image3]));
			w67.PackType = ((global::Gtk.PackType)(1));
			w67.Position = 0;
			w67.Expand = false;
			w67.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("label7");
			this.hbox6.Add (this.label9);
			global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label9]));
			w68.PackType = ((global::Gtk.PackType)(1));
			w68.Position = 1;
			w68.Expand = false;
			this.hbox3.Add (this.hbox6);
			global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.hbox6]));
			w69.PackType = ((global::Gtk.PackType)(1));
			w69.Position = 4;
			this.vbox3.Add (this.hbox3);
			global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox3]));
			w70.Position = 3;
			w70.Expand = false;
			w70.Fill = false;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
		}
	}
}
